USDA.ARS.GRIN.GGTools.WebUI/Controllers/ExplorerController.cs
using System.Web.Mvc;
using System;
using System.Collections.Generic;
using USDA.ARS.GRIN.GGTools.WebUI;
using USDA.ARS.GRIN.GGTools.ViewModelLayer;
using USDA.ARS.GRIN.GGTools.Taxonomy.ViewModelLayer;
using USDA.ARS.GRIN.GGTools.Taxonomy.DataLayer;
using NLog;

namespace USDA.ARS.GRIN.GGTools.WebUI.Controllers
{
    [GrinGlobalAuthentication]
    public class ExplorerController : BaseController
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();
        public ActionResult Index()
        {
            TaxonomyExplorerViewModel viewModel = new TaxonomyExplorerViewModel();
            try
            {
                return View("~/Views/Taxonomy/Explorer/Index.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }

        public PartialViewResult _LookupFamily(FamilyMapViewModel viewModel)
        {
            try
            {
                viewModel.Search();
                return PartialView("~/Views/Taxonomy/Explorer/_ListFamily.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }

        public PartialViewResult _LookupGenus(GenusViewModel viewModel)
        {
            try
            {
                viewModel.Search();
                return PartialView("~/Views/Taxonomy/Explorer/_ListGenus.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }

        public PartialViewResult _LookupSpecies(SpeciesViewModel viewModel)
        {
            try
            {
                viewModel.Search();
                return PartialView("~/Views/Taxonomy/Explorer/_ListSpecies.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }

        //public PartialViewResult _ListSpeciesFolderItems(int folderId)
        //{
        //    SpeciesViewModel viewModel = new SpeciesViewModel();
        //    try
        //    {
        //        viewModel.EventAction = "FOLDER";
        //        viewModel.SearchEntity.FolderID = sysFolderId;
        //        viewModel.GetFolderItems();
        //        return PartialView("~/Views/Taxonomy/Explorer/_List.cshtml", viewModel);
        //    }
        //    catch (Exception ex)
        //    {
        //        Log.Error(ex);
        //        return PartialView("~/Views/Error/_InternalServerError.cshtml");
        //    }
        //}

        public PartialViewResult _ListFamily()
        {
            TaxonomyExplorerViewModel viewModel = new TaxonomyExplorerViewModel();
            FamilyMapViewModel viewModelFamily = new FamilyMapViewModel();
            try
            {
                viewModelFamily.SearchEntity.FamilyName = "Poa";
                //viewModelFamily.Search();
                viewModel.DataCollectionFamily = viewModelFamily.DataCollection;
                return PartialView("~/Views/Taxonomy/Explorer/_ListFamily.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }

        //public PartialViewResult _LookupFamily()
        //{ 
        
        //}

        public PartialViewResult _ListGenus(int familyId = 0)
        {
            GenusViewModel viewModel = new GenusViewModel();
            try
            {
                if (familyId == 0)
                {
                   //TODO
                }
                else
                {
                    viewModel.SearchEntity.FamilyID = familyId;
                }

                viewModel.Search();
                return PartialView("~/Views/Taxonomy/Explorer/_ListGenus.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }
        public PartialViewResult _ListSpecies(int genusId = 0)
        {
            SpeciesViewModel viewModel = new SpeciesViewModel();
            try
            {
                viewModel.SearchEntity.GenusID = genusId;
                viewModel.Search();
                return PartialView("~/Views/Taxonomy/Explorer/_ListSpecies.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }
        //public PartialViewResult _ListRelatedFolders(string tableName = "")
        //{
        //    try
        //    {
        //        FolderViewModel viewModel = new FolderViewModel();
        //        viewModel.SearchEntity.CreatedByCooperatorID = AuthenticatedUser.CooperatorID;
        //        viewModel.SearchEntity.FolderType = tableName;
        //        viewModel.Search();
        //        return PartialView("~/Views/Taxonomy/Explorer/_ListFolders.cshtml", viewModel);
        //    }
        //    catch (Exception ex)
        //    {
        //        Log.Error(ex);
        //        return PartialView("~/Views/Error/_InternalServerError.cshtml");
        //    }
        //}
    }
}

USDA.ARS.GRIN.GGTools.WebUI/Controllers/NoteController.cs
using System.Web.Mvc;
using System;
using System.Collections.Generic;
using USDA.ARS.GRIN.GGTools.WebUI;
using USDA.ARS.GRIN.GGTools.Taxonomy.ViewModelLayer;
using USDA.ARS.GRIN.GGTools.Taxonomy.DataLayer;
using NLog;


namespace USDA.ARS.GRIN.GGTools.Taxonomy.WebUI.Controllers
{
    [GrinGlobalAuthentication]
    public class NoteController: BaseController
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();

        [HttpPost]
        public PartialViewResult Lookup(FormCollection formCollection)
        {
            string partialViewName = "~/Views/Shared/Modals/_NoteSelectList.cshtml";
            ReferenceViewModel viewModel = new ReferenceViewModel();

            if (!String.IsNullOrEmpty(formCollection["TableName"]))
            {
                viewModel.SearchEntity.TableName = formCollection["TableName"];
            }

            if (!String.IsNullOrEmpty(formCollection["Note"]))
            {
                viewModel.SearchEntity.SearchText = formCollection["Note"];
                viewModel.SearchEntity.SearchText = viewModel.SearchEntity.SearchText.Replace(" ", "%");
            }

            viewModel.SearchNotes();
            return PartialView(partialViewName, viewModel);
        }
    }
}

USDA.ARS.GRIN.GGTools.WebUI/Controllers/WebOrderRequestController.cs
using Newtonsoft.Json;
using NLog;
using System;
using System.CodeDom;
using System.Web.Mvc;
using USDA.ARS.GRIN.GGTools.DataLayer;
using USDA.ARS.GRIN.GGTools.ViewModelLayer;

namespace USDA.ARS.GRIN.GGTools.WebUI.Controllers
{
    [GrinGlobalAuthentication]
    public class WebOrderRequestController : BaseController
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();

        public ActionResult View(int entityId)
        { 
            WebOrderRequestViewModel viewModel = new WebOrderRequestViewModel();
            try 
            { 
                viewModel.Get(entityId);
                return View("~/Views/WebOrderRequest/View.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }
       
        public PartialViewResult _ListItems(int webOrderRequestId)
        {
            try
            {
                WebOrderRequestViewModel viewModel = new WebOrderRequestViewModel();
                viewModel.GetWebOrderRequestItems(webOrderRequestId);
                return PartialView("~/Views/WebOrder/_ListItems.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }
    
        public JsonResult SendEmail(WebOrderRequestViewModel viewModel)
        {
            try
            {
                viewModel.Entity.OwnedByWebUserID = AuthenticatedUser.WebUserID;
                viewModel.SendEmail();
                
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }
        
        [HttpPost]
        public JsonResult AddNote(int webOrderRequestId, string noteText)
        {
            try 
            {
                WebOrderRequestViewModel viewModel = new WebOrderRequestViewModel();
                viewModel.InsertWebOrderRequestActionNote(webOrderRequestId, noteText, AuthenticatedUser.WebUserID);
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }
        
        [HttpPost]
        public JsonResult SetStatus(WebOrderRequestViewModel viewModel)
        {
            try
            {
                viewModel.Get(viewModel.Entity.ID);
                viewModel.Entity.ModifiedByCooperatorID = AuthenticatedUser.CooperatorID;
                viewModel.Entity.WebUserID = AuthenticatedUser.WebUserID;
                viewModel.Entity.StatusCode = viewModel.NewActionCode;
                viewModel.Update();

                if (viewModel.IsEmailRequested)
                {
                    if ((viewModel.Entity.StatusCode != "NRR_HOLD") && (!viewModel.Entity.StatusCode.Contains("_REL")))
                    {
                        viewModel.SendEmail();
                    }
                }
                
                if (viewModel.IsBCCRequested)
                {
                    viewModel.SendEmail(viewModel.ActionEmailBCC);
                }

                return Json(new { success = true, data = viewModel.Entity.ID }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult SetLockStatus(int webOrderRequestId, string isLocked)
        {
            WebOrderRequestViewModel viewModel = new WebOrderRequestViewModel();

            try
            {
                viewModel.Get(webOrderRequestId);
                viewModel.Entity.IsLocked = (isLocked == "Y") ? true : false;
                viewModel.Entity.WebUserID = AuthenticatedUser.WebUserID;
                viewModel.NewActionCode = String.Empty;
                viewModel.UpdateLock();
                return Json(new { success = true, data = viewModel.Entity.ID }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult SetHoldStatus(int webOrderRequestId, string webOrderRequestAction, string holdOption)
        {
            WebOrderRequestViewModel viewModel = new WebOrderRequestViewModel();

            try
            {
                viewModel.InsertWebOrderRequestAction(new WebOrderRequestAction { ActionCode = webOrderRequestAction, WebOrderRequestID = webOrderRequestId, CreatedByWebUserID = AuthenticatedUser.WebUserID });

                if (webOrderRequestAction == "NRR_HOLD_CTRY")
                {
                    // TODO retrieve email template that corresponds to this action
                    viewModel.SendEmail();
                }
                return Json(new { success = true, data = viewModel.Entity.ID }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Index()
        {
            try
            {
                WebOrderRequestViewModel viewModel = new WebOrderRequestViewModel();
                viewModel.PageTitle = "NRR Tool Web Order Explorer";
                return View("~/Views/WebOrderRequest/Index.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }

        public ActionResult Search(int id=0, string status="", string requestorName="", string emailAddress="", string organization="", string countryDescription = "", string intendedUseCode="")
        {
            WebOrderRequestViewModel viewModel = new WebOrderRequestViewModel();

            try
            {
                if (id > 0)
                {
                    viewModel.SearchEntity.ID = id;
                    viewModel.Search();
                }

                if (!String.IsNullOrEmpty(status))
                {
                    viewModel.SearchEntity.StatusCode = status;
                    viewModel.Search();
                }

                if (!String.IsNullOrEmpty(organization))
                {
                    viewModel.SearchEntity.WebCooperatorOrganization = organization;
                    viewModel.Search();
                }

                if (!String.IsNullOrEmpty(countryDescription))
                {
                    viewModel.SearchEntity.WebCooperatorAddressCountryDescription = countryDescription;
                    viewModel.Search();
                }

                if (!String.IsNullOrEmpty(emailAddress))
                {
                    viewModel.SearchEntity.WebCooperatorEmailAddress = emailAddress;
                    viewModel.Search();
                }

                if (!String.IsNullOrEmpty(intendedUseCode))
                {
                    viewModel.SearchEntity.IntendedUseCode = intendedUseCode;
                    viewModel.Search();
                }
                return View("~/Views/WebOrderRequest/Index.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }

        [HttpPost]
        public ActionResult Search(WebOrderRequestViewModel viewModel)
        {
            try
            {
                viewModel.Search();
                ModelState.Clear();
                return View("~/Views/WebOrderRequest/Index.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }

        [HttpPost]
        public PartialViewResult SearchWebOrderRequestItems(string webOrderRequestIdList)
        {
            try
            {
                WebOrderRequestViewModel viewModel = new WebOrderRequestViewModel();
                viewModel.SearchEntity.IDList = webOrderRequestIdList;
                viewModel.SearchWebOrderRequestItems();
                return PartialView("~/Views/WebOrderRequest/_ListWebOrderRequestItems.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }

        [HttpPost]
        public PartialViewResult SearchWebOrderRequestActions(string webOrderRequestIdList)
        {
            try
            {
                WebOrderRequestViewModel viewModel = new WebOrderRequestViewModel();
                viewModel.SearchEntity.IDList = webOrderRequestIdList;
                viewModel.SearchWebOrderRequestActions();
                return PartialView("~/Views/WebOrderRequest/_ListWebOrderRequestActions.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }

        public ActionResult _Lookup(FormCollection formCollection)
        {

USDA.ARS.GRIN.GGTools.WebUI/Views/WebOrderRequest/Explorer/_Detail.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.WebOrderRequestViewModel

<style type="text/css">
    .scrollable-display-section {
        width: 100%; /* Flexible width */
        max-height: 100px; /* Fixed height */
        overflow-y: auto;
    }
</style>

<style type="text/css">
    .scrollable-table-section {
        width: 100%; /* Flexible width */
        max-height: 200px; /* Fixed height */
        overflow-y: auto;
    }
</style>

@if(Model.Entity.IsLocked == true)
{ 
    <div class="alert alert-info alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-lock"></i> Locked</h5>
        This web order request is being reviewed by <strong>@Model.Entity.OwnedByWebCooperatorName</strong> as of @Model.Entity.OwnedDate
    </div>
}

<div class="row">
    <div class="btn-group">
        @if (Model.Entity.StatusCode.Contains("NRR"))
        {
            if (Model.Entity.IsLocked == true && Model.Entity.OwnedByWebUserID == AppInfo.GetAuthenticatedUser().WebUserID)
            {
                <!-- On Hold -->
                if (Model.Entity.StatusCode == "NRR_HOLD")
                {
                    <button id="btnActionHoldRel"
                            data-ggtools-web-order-request-action="NRR_HOLD_REL"
                            type="button"
                            class="btn btn-default">
                        <i class="fas fa-unlock nav-icon"></i>
                        Remove Hold
                    </button>
                }
                else
                {
                    <button id="btnOpenModalHold"
                            data-ggtools-web-order-request-action="NRR_HOLD"
                            type="button"
                            class="btn btn-default">
                        <i class="fas fa-lock nav-icon"></i>
                        On Hold
                    </button>
                }

                <!-- On Country Hold -->
                if (Model.Entity.StatusCode == "NRR_HOLD_CTRY")
                {
                    <button id="btnActionHold"
                            data-ggtools-web-order-request-action="NRR_HOLD_CTRY_REL"
                            type="button"
                            class="btn btn-default">
                        <i class="fas fa-unlock nav-icon"></i>
                        Remove Country Hold
                    </button>
                }
                else
                {
                    <button id="btnOpenModalCountryHold"
                            data-ggtools-web-order-request-action="NRR_HOLD_CTRY"
                            type="button"
                            class="btn btn-default">
                        <i class="fas fa-lock nav-icon"></i>
                        On Country Hold
                    </button>
                }

                if (Model.Entity.StatusCode == "NRR_FLAG")
                {
                    <button id="btnOpenModalApprove"
                            data-ggtools-web-order-request-action="NRR_APPROVE"
                            type="button"
                            class="btn btn-default">
                        <i class="fas fa-thumbs-up text-green nav-icon"></i>
                        Approve
                    </button>
                    <button id="btnOpenModalReject"
                            data-ggtools-web-order-request-action="NRR_REJECT"
                            type="button"
                            class="btn btn-default">
                        <i class="fas fa-thumbs-down text-red nav-icon"></i>
                        Reject
                    </button>
                    <button id="btnOpenModalRequestInfo"
                            data-ggtools-web-order-request-action="NRR_INFO"
                            type="button"
                            class="btn btn-default">
                        <i class="fas fa-info text-blue nav-icon"></i>
                        Request Additional Information
                    </button>
                    <button id="btnOpenModalRequestInfo"
                            data-ggtools-web-order-request-action="NRR_CUR"
                            type="button"
                            class="btn btn-default">
                        <i class="fas fa-tree nav-icon"></i>
                        Email Curator(s)
                    </button>
                }
            }

            if (Model.Entity.IsLocked)
            {
                <button id="btnSetStatusUnLock"
                        type="button"
                        data-ggtools-is-locked="N"
                        class="btn btn-default float-right">
                    <i class="fas fa-unlock nav-icon"></i>
                    End Review
                </button>
            }
            else
            {
                <button id="btnSetStatusLock"
                        type="button"
                        data-ggtools-is-locked="Y"
                        class="btn btn-default float-right">
                    <i class="fas fa-lock nav-icon"></i>
                    Review/Edit
                </button>
            }


        }
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-1">
        <div class="form-group">
            <label>ID</label>
            <input type="text" value="@Model.Entity.ID" class="form-control form-control-sm" readonly="readonly" />
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <label>Status</label>
            @{
                string statusCssClass = String.Empty;
                switch (Model.Entity.StatusCode.ToUpper())
                {
                    case "ACCEPTED":
                        statusCssClass = "background-color: #28a745; color:white;";
                        break;
                    case "CANCELED":
                        statusCssClass = "background-color: #ffc107; color:white;";
                        break;
                    case "SUBMITTED":
                        statusCssClass = "background-color: #6f42c1; color:white;";
                        break;
                    case "MIXED":
                        statusCssClass = "background-color: #007bff; color:white;";
                        break;
                    case "NRR_FLAG":
                        statusCssClass = "background-color: red; color:white;";
                        break;
                    case "NRR_HOLD":
                        statusCssClass = "background-color:mediumvioletred; color:white;";
                        break;
                    case "NRR_HOLD_CTRY":
                        statusCssClass = "background-color:indigo; color:white;";
                        break;
                }
            }
            @Html.TextBoxFor(x => x.Entity.StatusTitle, new { @class = "form-control form-control-sm", @readonly = "readonly", disabled = "disabled", @style = statusCssClass })
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <label>Submitted By</label>
            <div class="input-group">
                @Html.TextBoxFor(x => x.Entity.WebCooperatorFullName, new { @class = "form-control form-control-sm", @readonly = "readonly", disabled = "disabled" })
                <span class="input-group-append">
                    <a href="@Url.Action("SetStatus","WebCooperator", new { @entityId = Model.Entity.WebCooperatorID })" class="btn btn-default btn-sm"><i class="fa fa-search"></i></a>
                </span>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <label>Email</label>
        @Html.TextBoxFor(x => x.Entity.WebCooperatorEmail, new { @class = "form-control form-control-sm", @readonly = "readonly", disabled = "disabled" })
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <label>Submitted</label>
            @Html.TextBoxFor(x => x.Entity.OrderDate, new { @class = "form-control form-control-sm", @readonly = "readonly", disabled = "disabled" })
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-6">
        <label>Requestor Address</label>
        <br />
        @Html.Raw(Model.Entity.WebCooperatorAddressFormatted)
    </div>
    <div class="col-md-6">
        <label>Shipping Address</label>
        <br />
        @Html.Raw(Model.Entity.ShippingAddressFormatted)
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label>Intended Use Note</label>

            <div class="scrollable-display-section">
                @Model.Entity.IntendedUseCode: @Html.Raw(Model.Entity.IntendedUseNote)
            </div>

        </div>
    </div>
</div>

@if (!String.IsNullOrEmpty(Model.Entity.SpecialInstruction))
{
    <div class="row">
        <div class="col-md-12">
            <label>Special Instruction</label>
            <p>@Model.Entity.SpecialInstruction</p>
        </div>
    </div>
}

@if (!String.IsNullOrEmpty(Model.Entity.Note))
{
    <div class="row">
        <div class="col-md-12">
            <label>Note</label>
            <p>@Model.Entity.Note</p>
        </div>
    </div>
}
<hr />
<div id="section-web-order-request-items">
    @Html.Partial("~/Views/WebOrderRequestItem/_List.cshtml")
</div>
@{ Html.RenderAction("_List", "OrderRequest", new { @webOrderRequestId = Model.Entity.ID }); }
<script type="text/javascript">
    //const makeScrollable = (div) => {
    //    div.style.overflowY = 'auto'; // Enables vertical scrolling
    //    div.style.maxHeight = '300px'; // Sets a maximum height
    //};

    //// Example usage
    //const div = document.getElementById('section-web-order-request-items');
    //makeScrollable(div);
</script>

USDA.ARS.GRIN.GGTools.WebUI/Views/WebOrderRequest/Explorer/_List.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.WebOrderRequestViewModel
<table id="data-table-web-order-requests" class="table table-striped ggtools" style="width:100%;">
    <thead>
        <tr>
            <th>ID</th>
            <th>Submitted</th>
            <th>Status</th>
            <th style="width: 20%">
                Requestor
            </th>
            <td>Email Address</td>
            <th>Organization</th>
            <th>Country</th>
            <th>Locked</th>
            <th></th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var result in Model.DataCollection)
        {
            string statusFieldBackgroundColorStyle = "";

            switch (result.StatusCode)
            {
                case "ACCEPTED":
                    statusFieldBackgroundColorStyle = "color:white;background-color:#00a65a;";
                    break;
                case "CANCELED":
                    statusFieldBackgroundColorStyle = "color:white;background-color:#f39c12;";
                    break;
                case "SUBMITTED":
                    statusFieldBackgroundColorStyle = "color:white;background-color:#605ca8;";
                    break;
                case "MIXED":
                    statusFieldBackgroundColorStyle = "color:white;background-color:blue;";
                    break;
                case "NRR_FLAG":
                    statusFieldBackgroundColorStyle = "color:white;background-color:red;";
                    break;
                case "NRR_HOLD":
                   statusFieldBackgroundColorStyle = "background-color:mediumvioletred; color:white;";
                    break;
                case "NRR_HOLD_CTRY":
                    statusFieldBackgroundColorStyle = "background-color:indigo; color:white;";
                    break;
                default:
                    statusFieldBackgroundColorStyle = "background-color:transparent;";
                    break;
            }
            <tr>

                <td>
                    @result.ID
                </td>
                <td>@result.CreatedDate.ToShortDateString()</td>
                <td style="@statusFieldBackgroundColorStyle">@result.StatusTitle</td>
                <td>
                    @result.WebCooperatorFullName
                </td>
                <td>
                    <a href="@Url.Action("Search","WebOrderRequest", new { emailAddress = result.WebCooperatorEmail })">@result.WebCooperatorEmail</a>
                </td>
                <td>
                    <a href="@Url.Action("Search","WebOrderRequest", new { organization = result.WebCooperatorOrganization })">@result.WebCooperatorOrganization</a>
                </td>
                <td>
                    <a href="@Url.Action("Search","WebOrderRequest", new { countryDescription = result.ShippingAddressCountryDescription })">@result.ShippingAddressCountryDescription</a>
                </td>
                <td>
                    
                    @{
                        if (result.IsLocked)
                        {
                            <span class="right badge badge-info">
                                <i class="fas fa-lock" style="color:white;"></i> @result.OwnedByWebCooperatorName
                            </span>
                        }
                    }
                </td>
                <td>
                    <a href="@Url.Action("View","WebOrderRequest", new { entityId = result.ID})" class="btn btn-default btn-flat btn-block">View</a>
                </td>
                
            </tr>
        }
    </tbody>
</table>