USDA.ARS.GRIN.GGTools.WebUI/Controllers/SysDynamicQueryController.cs
using NLog;
using System;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using USDA.ARS.GRIN.GGTools.ViewModelLayer;

namespace USDA.ARS.GRIN.GGTools.WebUI.Controllers
{
    public class SysDynamicQueryController : BaseController
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();
        // GET: DynamicQuery
        public ActionResult Index()
        {
            SysDynamicQueryViewModel viewModel = new SysDynamicQueryViewModel();
            ViewBag.PageTitle = "SQL Query Editor";
            return View(viewModel);
        }

        //public ActionResult Edit(int entityId)
        //{
        //    try
        //    {
        //        SysDynamicQueryViewModel viewModel = new SysDynamicQueryViewModel();
        //        viewModel.Entity.ID = entityId;
        //        viewModel.Edit();
        //        return Edit(viewModel);
        //    }
        //    catch (Exception ex)
        //    {
        //        Log.Error(ex);
        //        return PartialView("~/Views/Error/_InternalServerError.cshtml");
        //    }
        //}

        [HttpPost]
        public ActionResult Search(SysDynamicQueryViewModel viewModel)
        {
            string sqlQueryDrivingTable = String.Empty;

            try
            {
                if (!viewModel.Validate())
                {
                    if (viewModel.ValidationMessages.Count > 0) return View("~/Views/SysDynamicQuery/Index.cshtml", viewModel);
                }

                viewModel.Clean();

                // Save search if attribs supplied.
                if ((viewModel.EventAction == "SEARCH") && (viewModel.EventValue == "SAVE"))
                {
                    SysFolderViewModel sysFolderViewModel = new SysFolderViewModel();
                    sysFolderViewModel.Entity.CreatedByCooperatorID = AuthenticatedUser.CooperatorID;
                    sysFolderViewModel.Entity.Title = viewModel.EventInfo;
                    sysFolderViewModel.Entity.Description = viewModel.EventNote;
                    sysFolderViewModel.Entity.TableName = viewModel.TableName;
                    sysFolderViewModel.Entity.Properties = viewModel.SearchEntity.SQLStatement;
                    sysFolderViewModel.Entity.TypeCode = "SQL";
                    sysFolderViewModel.Insert();
                }

                // Execute user-defined search.
                viewModel.Search();
                ViewBag.PageTitle = "SQL Query Editor";
                return View("~/Views/SysDynamicQuery/Index.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                viewModel.ValidationMessages.Add(new Common.Library.ValidationMessage { Message = ex.Message });
                return View("~/Views/SysDynamicQuery/Index.cshtml", viewModel);
            }
        }

        [HttpPost]
        public PartialViewResult _Search(SysDynamicQueryViewModel viewModel)
        {
            try
            {
                //TODO: REFACTOR
                viewModel.SearchEntity.SQLStatement = viewModel.Entity.SQLStatement;

                if (!viewModel.Validate())
                {
                    if (viewModel.ValidationMessages.Count > 0) return PartialView("~/Views/SysDynamicQuery/_Edit.cshtml", viewModel);
                }

                //DEBUG Find tables in FROM clause (?)
                Regex regex = new Regex(@"\bJOIN\s+(?<Retrieve>[a-zA-Z\._\d\[\]]+)\b|\bFROM\s+(?<Retrieve>[a-zA-Z\._\d\[\]]+)\b|\bUPDATE\s+(?<Update>[a-zA-Z\._\d]+)\b|\bINSERT\s+(?:\bINTO\b)?\s+(?<Insert>[a-zA-Z\._\d]+)\b|\bTRUNCATE\s+TABLE\s+(?<DeleteAll>[a-zA-Z\._\d]+)\b|\bDELETE\s+(?:\bFROM\b)?\s+(?<DeleteAll>[a-zA-Z\._\d]+)\b");

                var obj = regex.Matches(viewModel.SearchEntity.SQLStatement);

                foreach (Match m in obj)
                {
                    var DEBUG = m.ToString().Substring(m.ToString().IndexOf(" ")).Trim();
                }

                // TODO POC: Based on "key" table in query, determine data type
                // of results.

                //viewModel.SearchEntity.SQLStatement = viewModel.SearchEntity.SQLStatement.Remove('\r');
                //viewModel.SearchEntity.SQLStatement = viewModel.SearchEntity.SQLStatement.Remove('\n');

                viewModel.Search();
                return PartialView("~/Views/SysDynamicQuery/_SearchResultsList.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                viewModel.ValidationMessages.Add(new Common.Library.ValidationMessage { Message = ex.Message });
                return PartialView("~/Views/SysDynamicQuery/_SearchResultsList.cshtml", viewModel);
            }
        }


        public PartialViewResult RenderEditModal()
        {
            try
            {
                SysDynamicQueryViewModel viewModel = new SysDynamicQueryViewModel();
                return PartialView("~/Views/SysDynamicQuery/Modals/_Edit.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }
        [HttpPost]
        //public PartialViewResult SaveSearch(SysDynamicQueryViewModel viewModel)
        //{
        //    try
        //    {
        //        viewModel.Entity.CreatedByCooperatorID = AuthenticatedUser.CooperatorID;
        //        //viewModel.SaveSearch();
        //        return PartialView("~/Views/SysDynamicQuery/Modals/_Edit.cshtml", viewModel);
        //    }
        //    catch (Exception ex)
        //    {
        //        Log.Error(ex);
        //        return PartialView("~/Views/Error/_InternalServerError.cshtml");
        //    }
        //}

        public PartialViewResult _Edit(int entityId)
        {
            SysDynamicQueryViewModel viewModel = new SysDynamicQueryViewModel();
            
            try
            {
                viewModel.SearchEntity.ID = entityId;
                viewModel.Search();
                return PartialView("~/Views/SysDynamicQuery/_Edit.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }

        //public PartialViewResult EditQuery(int entityId)
        //{
        //    SysFolderViewModel viewModel = new SysFolderViewModel();
        //    viewModel.Edit(entityId);
        //    return PartialView("~/Views/SysFolder/_EditQuery.cshtml", viewModel);
        //}

        //public PartialViewResult EditQuery(SysDynamicQueryViewModel viewModel)
        //{
        //    //TODO
        //    return PartialView("~/Views/SysFolder/_EditQuery.cshtml", viewModel);
        //}

        //[HttpPost]
        //public PartialViewResult _Edit(SysDynamicQueryViewModel viewModel)
        //{
        //    AppUserItemFolderViewModel appUserItemFolderViewModel = new AppUserItemFolderViewModel();
        //    AppUserItemListViewModel appUserItemListViewModel = new AppUserItemListViewModel();
        //    try
        //    {
        //        if (viewModel.Entity.ID > 0)
        //        {
        //            // TODO: REFACTOR -- CBH 11/8/23
        //            // Update folder.
        //            appUserItemFolderViewModel.SearchEntity.ID = viewModel.Entity.ID;
        //            appUserItemFolderViewModel.Search();
        //            appUserItemFolderViewModel.Entity.FolderName = viewModel.Entity.Title;
        //            appUserItemFolderViewModel.Entity.Description = viewModel.Entity.Description;
        //            appUserItemFolderViewModel.Entity.IsFavorite = viewModel.Entity.IsFavorite;
        //            appUserItemFolderViewModel.Entity.CreatedByCooperatorID = viewModel.Entity.CreatedByCooperatorID;
        //            appUserItemFolderViewModel.Entity.ModifiedByCooperatorID = viewModel.Entity.ModifiedByCooperatorID;
        //            appUserItemFolderViewModel.Update();

        //            // Update related app user item list record with any changes
        //            // to SQL statement.
        //            appUserItemListViewModel.SearchEntity.ID = viewModel.Entity.ParentID;
        //            appUserItemListViewModel.Search();
        //            appUserItemListViewModel.Entity.Properties = viewModel.Entity.SQLStatement;
        //            appUserItemListViewModel.Entity.ModifiedByCooperatorID = AuthenticatedUser.CooperatorID;
        //            appUserItemListViewModel.Update();
        //        }

        //        SysDynamicQueryViewModel sysDynamicQueryViewModel = new SysDynamicQueryViewModel();
        //        sysDynamicQueryViewModel.Entity.ID = viewModel.Entity.ID;
        //        sysDynamicQueryViewModel.Edit();
        //        return PartialView("~/Views/SysDynamicQuery/_Edit.cshtml", sysDynamicQueryViewModel);
        //    }
        //    catch (Exception ex)
        //    {
        //        Log.Error(ex);
        //        return PartialView("~/Views/Error/_InternalServerError.cshtml");
        //    }
        //}
        
        
    }
}

USDA.ARS.GRIN.GGTools.WebUI/Views/SysDynamicQuery/Edit.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.SysDynamicQueryViewModel
@{
    ViewBag.Title = Model.PageTitle;
    Layout = "~/Views/Shared/_LayoutAdminLTE3.cshtml";
}
@Html.HiddenFor(x => x.EventAction)
@Html.HiddenFor(x => x.EventValue)
@Html.HiddenFor(x => x.EventNote)
<div class="card">
    <div id="section-folder-options" class="card-header p-2">
        <ul class="nav nav-pills">
            <li id="tab-folder-detail" class="nav-item"><a class="nav-link active" href="#tab-content-detail" data-toggle="tab">Details</a></li>
            <li id="tab-folder-sharing" class="nav-item"><a class="nav-link" href="#tab-content-sharing" data-toggle="tab">Sharing</a></li>
        </ul>
    </div>
    <div class="card-body" id="section-search-criteria">
        <div class="tab-content">
            <div class="tab-pane active" id="tab-content-detail">
                @Html.Partial("~/Views/SysDynamicQuery/_Edit.cshtml")
            </div>
            <div class="tab-pane" id="tab-content-sharing">
                <div id="section_folder_cooperator_widget">
                    @{Html.RenderAction("RenderWidget", "AppUserItemFolderCooperatorMap", new { @appUserItemFolderId = Model.Entity.ID });}
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer">
        @if (Model.Entity.ID > 0)
        {
            <button id="btnDelete" type="button" class="btn btn-danger">
                Delete
            </button>
        }
        <button id="btnAddCooperator" class="btn btn-default float-right" data-toggle="modal" data-target="#modal-folder-edit-cooperators">
            <i class="fas fa-users"></i>
            Edit Sharing Options
        </button>
    </div>
</div>

<div id="section_search_results">

</div>

@Html.Partial("~/Views/Taxonomy/Shared/Modals/_Delete.cshtml")
@{Html.RenderAction("RenderEditModal", "AppUserItemFolderCooperatorMap", new { @appUserItemFolderId = Model.Entity.ID });}
@{Html.RenderAction("RenderFolderItemDeleteModal", "AppUserItemFolder", new { @entityId = Model.Entity.ID });}

<script type="text/javascript">
    $(document).ready(function () {
        Init();
    });

    function Init() {
        var isReadOnly = $("#IsReadOnly").val();
        if (isReadOnly == "Y") {
            SetReadOnly();
        }
    }

    /*
    * ***********************************************************
    * Folder item logic
    * ***********************************************************
    */
    function Load() {
        var eventAction = $("#EventAction").val();
        var eventValue = $("#EventValue").val();
        var tableName = $("#EventNote").val();
        LoadFolderItems(tableName, eventAction, eventValue);
    }

    function LoadFolderItems(tableName, eventAction, eventValue) {
        var id = $("#Entity_ID").val();
        var link = '@Url.Action("EVENT_VALUE", "EVENT_ACTION")';



        link = link.replace("EVENT_VALUE", eventValue);
        link = link.replace("EVENT_ACTION", eventAction);
        //tableName = tableName.replace("link-","");

        //DEBUG
        /*alert("DEBUG TAB " + tableName + " ACT " + eventAction + " VAL " + eventValue);*/

        $("#EventAction").val(eventAction);
        $("#EventValue").val(eventValue);
        $("#EventNote").val(tableName);

        var formData = new FormData();

        formData.append("appUserItemFolderId", id);
        //DEBUG
        //alert("ID IS " + id + " EVENT VALUE IS " + eventValue + " EVENT ACTION IS " + eventAction);

        /*$("#section-tab-overlay").show();*/

        $.ajax({
            url: link,
            type: 'POST',
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (response) {
                $("#tab-sys-tables-content").html(response);
                $("#section-tab-overlay").hide();
            },
            error: function () {
                alert("Error calling " + link);
                $("#section-tab-overlay").hide();
            }
        });
    }

    /*
    * ***********************************************************
    * Deletion logic
    * ***********************************************************
    */
    $(document).on("click", "[id='btnDeleteBatch']", function () {
        DeleteBatch();
    });

    function DeleteBatchPrompt() {
        var tableName = $("#EventNote").val();
        var selectedFolderItems = GetSelectedAppUserItemListIDs("data_table_" + tableName);
        $("#section-item-count").html(selectedFolderItems.length);
        $("#modal-batch-delete-confirm").modal("show");
    }

    function DeleteBatch() {
        var link = '@Url.Action("DeleteItems","AppUserItemFolder")';
        var refreshLink = '@Url.Action("Index","Taxonomy")';
        var folderId = $("#Entity_ID").val();
        var tableName = $("#EventNote").val();
        var selectedFolderItems = GetSelectedAppUserItemListIDs("data_table_" + tableName);
        var formData = new FormData();

        $("#ItemIDList").val(selectedFolderItems);

        formData.append("FolderID", folderId);
        formData.append("ItemIDList", selectedFolderItems);

        $("#section-item-count").html(selectedFolderItems.length);
        /*$("#modal-batch-delete-confirm").modal("show");*/

        $.ajax({
            url: link,
            type: 'POST',
            cache: false,
            dataType: 'json',
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                Load();
            },
            error: function (ex) {
            }
        });
    }

    /*
    * ***********************************************************
    * Sharing logic
    * ***********************************************************
    */
    $('#section-folder-options ul.nav li').on('click', function () {
        var id = $(this).attr('id');
        if (id == "tab-folder-sharing") {
            var folderId = $("#Entity_ID").val();
            //LoadAvailableCollaborators(folderId);
            //LoadCurrentCollaborators(folderId);
        }
    });

    function RenderFolderCooperatorWidget() {
        var link = '@Url.Action("RenderWidget", "AppUserItemFolderCooperatorMap")';
        var folderId = $("#Entity_ID").val();
        var formData = new FormData();

        formData.append("appUserItemFolderId", folderId);

        $.ajax({
            url: link,
            type: 'POST',
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (response) {
                $("#section_folder_cooperator_widget").html(response);
            },
            error: function () {
                alert("Error loading folder-sharing widget");
            }
        });
    }
</script>

USDA.ARS.GRIN.GGTools.WebUI/Views/SysDynamicQuery/Index.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.SysDynamicQueryViewModel
@{
    ViewBag.Title = "Dynamic Query";
    Layout = "~/Views/Shared/_LayoutAdminLTE3.cshtml";
}
@Html.HiddenFor(x => x.RowsAffected)
<div class="row">
    <div class="col-md-12">
        @Html.Partial("~/Views/SysDynamicQuery/_Detail.cshtml")
        @Html.Partial("~/Views/SysDynamicQuery/_SearchResultsList.cshtml")
    </div>
</div>
@{Html.RenderAction("GetDynamicEditModal", "SysFolder", new { @sysTableName = Model.TableName, @typeCode = "SQL" }); }
<script type="text/javascript">
    $('.table-selector').on('click', function () {
        var data = $(this).attr('id');
        var sql = "SELECT * FROM TABLE_NAME";
        sql = sql.replace("TABLE_NAME", data);
        $("#txtSQL").val(sql);
    });

    $('.field-selector').on('click', function () {
        var data = $(this).attr('id');
        alert("DEBUG FIELD IS " + data);
    });
</script>

USDA.ARS.GRIN.GGTools.WebUI/Views/SysDynamicQuery/_Detail.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.SysDynamicQueryViewModel
<div id="section-folder-confirmation"></div>

@using (Html.BeginForm("Search", "SysDynamicQuery", FormMethod.Post, new { id = "frmMain" }))
{
    @Html.HiddenFor(x => x.EventAction)
    @Html.HiddenFor(x => x.EventValue)
    @Html.HiddenFor(x => x.EventInfo)
    @Html.HiddenFor(x => x.EventNote)
    @Html.HiddenFor(x => x.TableName)
    

    <div class="card">
        <div class="card-header p-2">
            <ul class="nav nav-pills">
                <li class="nav-item"><a class="nav-link active" href="#section-search-criteria" data-toggle="tab">Search Criteria</a></li>
                <li class="nav-item"><a class="nav-link" href="#timeline" data-toggle="tab">Saved Searches</a></li>
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content">
                @Html.Partial("~/Views/Shared/_ValidationMessages.cshtml")
                
                @*@Html.Partial("~/Views/Shared/_UserMessages.cshtml")*@
                <div class="tab-pane active" id="section-search-criteria">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>
                                    SQL Statement
                                    &nbsp;<i class="fas fa-info-circle" style="color:#17a2b8;"></i>
                                </label>
                                <div id="section-panel-help" class="alert alert-info alert-dismissible" style="display: none;">
                                    <button type="button" class="close" aria-hidden="true">×</button>
                                    <h5><i class="icon fas fa-info"></i> SQL Query Guidelines</h5>
                                    <ul>
                                        <li>
                                            Queries cannot contain INSERT, UPDATE, or DELETE clauses.
                                        </li>
                                        <li>
                                            For the purposes of creating a folder, the query engine will attempt determine the record data type based on the first table named in the FROM clause.
                                        </li>
                                    </ul>
                                </div>
                                @Html.TextAreaFor(x => x.SearchEntity.SQLStatement, new { @id = "txtSQL", @class = "form-control", @rows = "10" })
                            </div>
                        </div>
                    </div>
                    <div>
                        <button id="btnReset" type="button" class="btn btn-default">Reset</button>
                        <div class="btn-group float-right">
                            <button id="btnSubmitSysDynamicQuery" type="submit" class="btn btn-default">Search</button>
                            <button type="button" class="btn btn-default dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <div class="dropdown-menu" role="menu" style="">
                                <a id="btnOpenDynamicFolderModal" class="dropdown-item" href="#">Save Search</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="timeline">
                    <div class="row">
                        <div class="col-md-12">
                            @Html.Partial("~/Views/SysDynamicQuery/_List.cshtml")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $(".fa-info-circle").on('click', function (event) {
        event.stopPropagation();
        event.stopImmediatePropagation();
        /*alert("CLICK");*/
        if ($("#section-panel-help").is(":visible")) {
            //
        } else {
            $("#section-panel-help").show();
        }
    });

    $(".close").on('click', function (event) {
        $("#section-panel-help").hide();
    });
</script>

USDA.ARS.GRIN.GGTools.WebUI/Views/SysDynamicQuery/_Edit.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.SysDynamicQueryViewModel
@Html.Partial("~/Views/Shared/_RevisionHistory.cshtml")
@using (Html.BeginForm("_Edit", "SysDynamicQuery", FormMethod.Post, new { id = "frmEdit" }))
{
    @Html.HiddenFor(x => x.PageTitle)
    @Html.HiddenFor(x => x.TableName)
    @Html.HiddenFor(x => x.TableCode)
    @Html.HiddenFor(x => x.Entity.ParentID)
    @Html.HiddenFor(x => x.Entity.ID)
    @Html.HiddenFor(x => x.Entity.RelatedItemCount)
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Name</label>
                @Html.TextBoxFor(x => x.Entity.Title, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>Description</label>
                @Html.TextBoxFor(x => x.Entity.Description, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group clearfix">
                <div class="icheck-primary d-inline">
                    @Html.CheckBoxFor(x => x.Entity.IsFavoriteOption, new { id = "cbxIsFavorite", @type = "checkbox", @class = "custom-control-input" })
                    <label for="cbxIsFavorite">
                        Add this folder to my Favorites list.
                    </label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label>
                    SQL Statement
                    &nbsp;<i class="fas fa-info-circle" style="color:#17a2b8;"></i>
                </label>
                @Html.TextAreaFor(x => x.Entity.SQLStatement, new { @class = "form-control", @rows = "10" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="margin">
                <button id="btnSaveSysDynamicQuery" type="button" class="btn btn-default float-right"><i class="fas fa-save"></i> Save Edits</button>
                <button id="btnRunSysDynamicQuery" type="button" class="btn btn-default"><i class="fas fa-running"></i> Run Query</button>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $("#btnSaveSysDynamicQuery").click(function () {
        SaveSysDynamicQuery();
    });

    $("#btnRunSysDynamicQuery").click(function () {
        RunSysDynamicQuery();
    });

    function SaveSysDynamicQuery() {
        var link = '@Url.Action("_Edit", "SysDynamicQuery")';
        var formData = new FormData();

        if ($('#cbxIsFavorite').prop('checked') == true) {
            formData.append("Entity.IsFavorite", "Y");
        }

        formData.append("Entity.ParentID", $("#Entity_ParentID").val());
        formData.append("Entity.ID", $("#Entity_ID").val());
        formData.append("Entity.Title", $("#Entity_Title").val());
        formData.append("Entity.Description", $("#Entity_Description").val());
        formData.append("Entity.SQLStatement", $("#Entity_SQLStatement").val());

        //DEBUG
        /*alert("EVENT VAL " + eventValue + " PARENT ENTITY " + entityId);*/

        $.ajax({
            url: link,
            type: 'POST',
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (response) {
                $("#tab-content-detail").html(response);
            },
            error: function () {
                alert("Error");
            }
        });
        $("#modal-folder-edit").modal("hide");
    }

    function RunSysDynamicQuery() {
        var link = '@Url.Action("_Search", "SysDynamicQuery")';
        var formData = new FormData();

        formData.append("Entity.SQLStatement", $("#Entity_SQLStatement").val());

        //DEBUG
        /*alert("EVENT VAL " + eventValue + " PARENT ENTITY " + entityId);*/

        $.ajax({
            url: link,
            type: 'POST',
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (response) {
                $("#section_search_results").html(response);
            },
            error: function () {
                alert("Error");
            }
        });
        $("#modal-folder-edit").modal("hide");
    }
</script>

USDA.ARS.GRIN.GGTools.WebUI/Views/SysDynamicQuery/_List.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.SysDynamicQueryViewModel
<table id="data_table_app_user_item_folder" class="table table-striped folder-table" style="width:100%;">
    <thead>
        <tr>
            <th></th>
            <th>ID</th>
            <th>
                <i class="fa fa-star"></i>
            </th>
            <th><i class="fa fa-users"></i></th>
            <th>Name</th>
            <th>Description</th>
            <th>Created</th>
            <th>By</th>
            @*<th>Modified</th>
                <th>By</th>*@
            @*<th style="text-align:center;">Items</th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var folder in Model.DataCollectionAppUserItemFolders)
        {
            <tr>
                <td>
                    @folder.ID
                </td>
                <td>
                    @folder.ID
                </td>
                <td class="mailbox-star">
                    @if (folder.IsFavorite == "Y")
                    {
                        <a href="#"><i class="fa fa-star text-yellow"></i></a>
                    }
                </td>
                <td>
                    @if (folder.IsShared == "Y")
                    {
                        <a href="#"><i class="fa fa-users text-blue"></i></a>
                    }
                </td>
                <td>
                    @folder.FolderName
                </td>
                <td>@folder.Description</td>
                <td>@folder.CreatedDate.ToShortDateString()</td>
                <td>@folder.CreatedByCooperatorName</td>
                @*<td>
                        @if (folder.ModifiedDate > DateTime.MinValue)
                        {
                            @folder.ModifiedDate.ToShortDateString()
                        }
                    </td>
                    <td>@folder.ModifiedByCooperatorName</td>*@
                @*<td style="text-align:center;">
                        <span class="badge bg-gray" style="font-size:11pt;">
                            @folder.TotalItems
                        </span>
                    </td>*@
                <td style="text-align:right;">
                    <a href="@Url.Action("Edit", "SysDynamicQuery", new { entityId = folder.ID })" class="btn btn-default btn-sm pull-right row-edit">
                        <i class="fa fa-edit"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function () {
        InitDataTable("data_table_app_user_item_folder");
    });
</script>