USDA.ARS.GRIN.GGTools.WebUI/Controllers/CropForCWRController.cs
using System.Web.Mvc;
using System;
using System.Collections.Generic;
using USDA.ARS.GRIN.GGTools.WebUI;
using USDA.ARS.GRIN.GGTools.ViewModelLayer;
using USDA.ARS.GRIN.GGTools.Taxonomy.ViewModelLayer;
using USDA.ARS.GRIN.GGTools.Taxonomy.DataLayer;
using NLog;

namespace USDA.ARS.GRIN.GGTools.Taxonomy.WebUI.Controllers
{
    [GrinGlobalAuthentication]
    public class CropForCWRController : BaseController
    {
        protected static string BASE_PATH = "~/Views/Taxonomy/CropForCWR/";
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();
       
        public ActionResult Index(string eventAction = "", int folderId = 0)
        {
            CropForCWRViewModel viewModel = new CropForCWRViewModel();
            try
            {
                viewModel.AuthenticatedUserCooperatorID = AuthenticatedUser.CooperatorID;
                viewModel.TableName = "taxonomy_cwr_crop";
                viewModel.TableCode = "CropForCWR";

                var DEBUG = ViewBag.PageTitle;

                string targetKey = this.ControllerContext.RouteData.Values["controller"].ToString().ToUpper() + "_SEARCH";
                if (Session[targetKey] != null)
                {
                    viewModel = Session[targetKey] as CropForCWRViewModel;
                }

                if (eventAction == "RUN_SEARCH")
                {
                    AppUserItemListViewModel appUserItemListViewModel = new AppUserItemListViewModel();
                    appUserItemListViewModel.SearchEntity.AppUserItemFolderID = folderId;
                    appUserItemListViewModel.Search();
                    viewModel.SearchEntity = viewModel.Deserialize<CropForCWRSearch>(appUserItemListViewModel.Entity.Properties);
                    viewModel.Search();
                }

                return View(BASE_PATH + "Index.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }
        
        public PartialViewResult _ListFolderItems(int sysFolderId)
        {
            CropForCWRViewModel viewModel = new CropForCWRViewModel();
            try
            {
                viewModel.EventAction = "FOLDER";
                viewModel.SearchEntity.FolderID = sysFolderId;
                viewModel.GetFolderItems();
                return PartialView(BASE_PATH + "_ListFolder.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }
        
        [HttpPost]
        public PartialViewResult _Search(FormCollection formCollection)
        {
            CropForCWRViewModel vm = new CropForCWRViewModel();

            if (!String.IsNullOrEmpty(formCollection["Name"]))
            {
                vm.SearchEntity.Name = formCollection["Name"];
                vm.EventAction = "search";
            }
            ModelState.Clear();
            return PartialView("~/Views/CropForCWR/_SelectList.cshtml", vm);
        }

        public PartialViewResult _Search()
        { return PartialView("~/Views/CropForCWR/_Search.cshtml", new CropForCWRViewModel()); }
        
        [HttpPost]
        public ActionResult Search(CropForCWRViewModel viewModel)
        {
            try
            {
                Session[SessionKeyName] = viewModel;
                viewModel.EventAction = "SEARCH";
                viewModel.Search();
                ModelState.Clear();

                // Save search if attribs supplied.
                if ((viewModel.EventAction == "SEARCH") && (viewModel.EventValue == "SAVE"))
                {
                    viewModel.AuthenticatedUserCooperatorID = AuthenticatedUser.CooperatorID;
                    //viewModel.SaveSearch();
                }

                return View(BASE_PATH + "Index.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }
        [HttpPost]
        public PartialViewResult Lookup(CropForCWRViewModel viewModel)
        {
            string partialViewName = "~/Views/Taxonomy/CropForCWR/Modals/_SelectList.cshtml";

            try
            {
                viewModel.Search();
                return PartialView(partialViewName, viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }
        public ActionResult Add()
        {
            try
            {
                CropForCWRViewModel viewModel = new CropForCWRViewModel();
                viewModel.TableName = "taxonomy_cwr_crop";
                viewModel.PageTitle = "Add Crop For CWR";
                viewModel.AuthenticatedUserCooperatorID = AuthenticatedUser.CooperatorID;
                return View(BASE_PATH + "Edit.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }

        [HttpPost]
        public JsonResult Add(FormCollection formCollection)
        {
            throw new NotImplementedException();
        }

        public ActionResult Edit(int entityId = 0, int appUserItemFolderId = 0)
        {
            try
            {
                CropForCWRViewModel viewModel = new CropForCWRViewModel();
                viewModel.TableName = "taxonomy_cwr_crop";
                viewModel.TableCode = "CropForCWR";
                viewModel.PageTitle = String.Format("Edit Crop For CWR [{0}]", entityId);
                viewModel.AuthenticatedUserCooperatorID = AuthenticatedUser.CooperatorID;
                viewModel.Get(entityId);
                return View(BASE_PATH + "Edit.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }

        [HttpPost]
        public ActionResult Edit(CropForCWRViewModel viewModel)
        {
            try
            {
                if (!viewModel.Validate())
                {
                    if (viewModel.ValidationMessages.Count > 0) return View(viewModel);
                }

                if (viewModel.Entity.ID == 0)
                {
                    viewModel.Entity.CreatedByCooperatorID = AuthenticatedUser.CooperatorID;
                    viewModel.Insert();
                }
                else
                {
                    viewModel.Entity.ModifiedByCooperatorID = AuthenticatedUser.CooperatorID;
                    viewModel.Update();
                }
                return RedirectToAction("Edit", "CropForCWR", new { entityId = viewModel.Entity.ID });
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }

        [HttpPost]
        public ActionResult Delete(FormCollection formCollection)
        {
            try
            {
                CropForCWRViewModel viewModel = new CropForCWRViewModel();
                viewModel.Entity.ID = Int32.Parse(GetFormFieldValue(formCollection, "EntityID"));
                viewModel.TableName = GetFormFieldValue(formCollection, "TableName");
                viewModel.Delete();
                return View();
            }
            
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }

        [HttpPost]
        public JsonResult DeleteEntity(FormCollection formCollection)
        {
            try 
            {
                CropForCWRViewModel viewModel = new CropForCWRViewModel();
                viewModel.Entity.ID = Int32.Parse(GetFormFieldValue(formCollection, "EntityID"));
                viewModel.TableName = GetFormFieldValue(formCollection, "TableName");
                viewModel.Delete();
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { errorMessage = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public PartialViewResult RenderLookupModal()
        {
            CropForCWRViewModel viewModel = new CropForCWRViewModel();
            return PartialView(BASE_PATH + "/Modals/_Lookup.cshtml", viewModel);
        }
    }
}

USDA.ARS.GRIN.GGTools.WebUI/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using USDA.ARS.GRIN.GGTools.DataLayer;
using USDA.ARS.GRIN.GGTools.ViewModelLayer;

namespace USDA.ARS.GRIN.GGTools.WebUI.Controllers
{
    public class MenuController : BaseController
    {
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult GetMenu(string eventAction, string eventValue, int entityId = 0)
        {
            MenuViewModel viewModel = new MenuViewModel();
            string viewName = "~/Views/Components/_DefaultMenu.cshtml"; 
            viewModel.EntityID = entityId;
            viewModel.EventAction = eventAction;
            viewModel.EventValue = eventValue;

            eventAction = eventAction.ToLower();
            eventValue = eventValue.ToLower();

            //// Determine whether user can edit the table being accessed.
            SysUser authenticatedUser = AuthenticatedUser;
            //if (authenticatedUser.CanEdit(eventValue)) { }

            // Handle "Index" (home) pages
            if (eventValue == "index")
            {
                switch (eventAction)
                {
                    case "home":
                    case "taxonomy":
                        viewName = "~/Views/Components/_DefaultMenu.cshtml";
                        break;
                    case "species":
                        viewName = "~/Views/Taxonomy/Species/Components/_SearchMenu.cshtml";
                        break;
                    case "geographymap":
                        viewName = "~/Views/Taxonomy/GeographyMap/Components/_SearchMenu.cshtml";
                        break;
                    default:
                        viewName = "~/Views/Components/_DefaultSearchMenu.cshtml";
                        break;
                }
            }



            if ((eventValue == "add") || (eventValue == "edit"))
            {
                if ((eventAction == "family") || (eventAction == "genus") || (eventAction == "species"))
                {
                    // Load context-based menu for the current taxon type.
                    viewName = "~/Views/Taxonomy/" + eventAction + "/Components/_EditMenu.cshtml";
                }
                else
                {
                    if (eventAction == "classification")
                    {
                        viewName = "~/Views/Taxonomy/Order/Components/_EditMenu.cshtml";
                    }
                    else 
                    {
                        if (eventAction == "sysfolder")
                        {
                            viewName = "~/Views/Components/_DefaultMenu.cshtml";
                        }
                        else
                        {
                            viewName = "~/Views/Components/_DefaultEditMenu.cshtml";
                        }
                    }
                }
            }
            return PartialView(viewName, viewModel);
        }
    }
}

USDA.ARS.GRIN.GGTools.WebUI/Controllers/TaxonomyController.cs
using NLog;
using System;
using System.Web.Mvc;
using USDA.ARS.GRIN.GGTools.ViewModelLayer;

namespace USDA.ARS.GRIN.GGTools.WebUI.Controllers
{
    [GrinGlobalAuthentication]
    public class TaxonomyController : BaseController
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();
        public ActionResult Index()
        {
            HomeViewModel viewModel = new HomeViewModel();
            viewModel.AuthenticatedUser = AuthenticatedUser;
            //return Edit("~/Views/Taxonomy/Home/Index.cshtml", viewModel);
            return RedirectToAction("Explorer","SysFolder");
        }
        public ActionResult Admin(int sysUserId = 0)
        {
            SysUserViewModel viewModel = new SysUserViewModel();

            try
            {
                return View("~/Views/Taxonomy/Admin/Index.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }
        public PartialViewResult RenderSidebar()
        {
            return PartialView("~/Views/Shared/Sidebars/_MainSidebarTaxonomy.cshtml");
        }
    }
}

USDA.ARS.GRIN.GGTools.WebUI/Views/Taxonomy/CropForCWR/Edit.cshtml
@model USDA.ARS.GRIN.GGTools.Taxonomy.ViewModelLayer.CropForCWRViewModel
@{
    ViewBag.Title = Model.PageTitle;
    Layout = null;
}

@{
    string eventAction = @ViewContext.RouteData.Values["controller"].ToString();
    string eventValue = @ViewContext.RouteData.Values["action"].ToString();
}

<!DOCTYPE html>
<html lang="en">
@Html.Partial("~/Views/Shared/_Head.cshtml")
<body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <nav class="main-header navbar navbar-expand-md navbar-light text-sm">
            <div class="container" style="max-width:1500px;">
                <a href="@Url.Action("Index","Home")" class="navbar-brand">
                    <img src="~/dist/img/GGlogo_BW.gif" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                    <span class="brand-text font-weight-light">GGTools</span>
                </a>
                <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                    @{Html.RenderAction("GetMenu", "Menu", new { @eventAction = eventAction, @eventValue = eventValue });}
                </div>
                <!-- BEGIN RIGHT-ALIGNED NAV MENU -->
                <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                    @if (Model.Entity.ID > 0)
                    {
                        string url = String.Format("https://training.ars-grin.gov/gringlobal/taxon/cwrcropdetail?id={0}&type=crop", Model.Entity.ID);
                        <li id="nav-item-view-website" class="nav-item">
                            <a class="nav-link" href="@url">
                                <i class="far fa-globe"></i>
                                View on Website
                            </a>
                        </li>
                    }
                    @Html.Partial("~/Views/Shared/_NavbarRight.cshtml")
                </ul>
                <!-- END RIGHT-ALIGNED NAV MENU -->
            </div>
        </nav>
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container" style="max-width:1500px;">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">
                                @Html.Raw(ViewBag.Title)
                            </h1>
                        </div>
                        <div class="col-sm-6">
                            @Html.Partial("~/Views/Taxonomy/Shared/_Breadcrumbs.cshtml")
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container" style="max-width:1500px;">
                    <div id="section-folder-confirmation"></div>
                    @using (Html.BeginForm("Edit", "CropForCWR", FormMethod.Post, new { id = "frmEdit" }))
                    {
                        @Html.HiddenFor(x => x.PageTitle)
                        @Html.HiddenFor(x => x.EventAction)
                        @Html.HiddenFor(x => x.EventValue)
                        @Html.HiddenFor(x => x.TableName)
                        @Html.HiddenFor(x => x.TableCode)
                        @Html.HiddenFor(x => x.Entity.ID)
                        @Html.HiddenFor(x => x.Entity.RelatedItemCount)
                        @Html.Partial("~/Views/Taxonomy/Shared/_RevisionHistory.cshtml")
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Summary</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                @Html.Partial("~/Views/Shared/_ValidationMessages.cshtml")
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Name</label>
                                            @Html.TextBoxFor(x => x.Entity.CropForCWRName, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(x => x.Entity.CropForCWRName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <!-- BEGIN NOTE FIELD -->
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>
                                                Note
                                                &nbsp;<a href="" data-toggle="modal" data-target="#modal-note-lookup"><i class="fa fa-search"></i></a>
                                            </label>
                                            <div class="input-group">
                                                @Html.TextAreaFor(x => x.Entity.Note, new { @id = "txtNote", @class = "form-control", @style = "width:100%;" })
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>

                            </div>
                            <div class="card-footer">
                                <a href="@Url.Action("Refresh")" class="btn btn-default">Reset</a>

                                @if (Model.Entity.ID > 0)
                                {
                                    <button id="btnDelete" type="button" class="btn btn-danger">
                                        Delete
                                    </button>
                                }
                                <button type="submit" class="btn btn-default float-right">Save</button>
                            </div>
                        </div>
                    }

                    @if (Model.Entity.ID > 0)
                    {
                        { Html.RenderAction("_List", "CWRMap", new { cropForCwrId = Model.Entity.ID }); }
                    }

                    @Html.Partial("~/Views/Shared/Modals/_NoteLookup.cshtml")
                    @Html.Partial("~/Views/Taxonomy/Shared/Modals/_Delete.cshtml")
                    @{Html.RenderAction("GetEditModal", "SysFolder", new { sysTableName = Model.TableName }); }
                </div>
            </div>
        </div>
        <aside class="control-sidebar control-sidebar-dark">
        </aside>
        <!-- Main Footer -->
        @Html.Partial("~/Views/Shared/_Footer.cshtml")
    </div>
</body>
</html>
<script type="text/javascript">
    $(document).ready(function () {
        //var formSubmitting = false;
        //var setFormSubmitting = function () { formSubmitting = true; };

        //var dirty = false;
        //$(document).on('change', 'input:not(.noWarning),textarea:not(.noWarning),select:not(.noWarning)', function () {
        //    dirty = true;
        //});

        //function checkDirty() {
        //    if (dirty) {
        //        alert('You have unsaved changes');
        //        return false;
        //    }
        //    return true;
        //}
        //// for non-AJAX pages
        //window.onbeforeunload = function (e) {
        //    if (!formSubmitting) {
        //        return checkDirty();
        //    }
        //};
        //// for AJAX pages
        //$('.ajax_navigation_tab').on('click', function () {
        //    if (!checkDirty()) {
        //        // do the ajax thing
        //        dirty = false;
        //    }
        //});

        //$("#frmEdit").on("submit", function (event) {
        //    setFormSubmitting();
        //});

    });

</script>


@Html.Partial("~/Views/Shared/_Scripts.cshtml")

USDA.ARS.GRIN.GGTools.WebUI/Views/Taxonomy/CropForCWR/Index.cshtml
@model USDA.ARS.GRIN.GGTools.Taxonomy.ViewModelLayer.CropForCWRViewModel
@{
    ViewBag.Title = Model.PageTitle;
    Layout = "~/Views/Shared/_LayoutAdminLTE3.cshtml";
}

@using (Html.BeginForm("Search", "CropForCWR", FormMethod.Post, new { id = "frmMain" }))
{
    @Html.HiddenFor(x => x.EventAction)
    @Html.HiddenFor(x => x.EventValue)
    @Html.HiddenFor(x => x.TableName)
    @Html.HiddenFor(x => x.TableCode)
    @Html.HiddenFor(x => x.PageTitle)
    @Html.HiddenFor(x => x.AuthenticatedUserCooperatorID)
    @Html.HiddenFor(x => x.ItemIDList)
    @Html.Partial("~/Views/Taxonomy/CropForCWR/_Detail.cshtml")
}

<div id="section-search-results">
    @Html.Partial("~/Views/Taxonomy/CropForCWR/_List.cshtml")
</div>

@{Html.RenderAction("GetDynamicEditModal", "SysFolder", new { @sysTableName = Model.TableName, @typeCode = "DYN" }); }
@{Html.RenderAction("GetEditModal", "SysFolder", new { @sysTableName = Model.TableName }); }

<script type="text/javascript">

    //$(document).keypress(function (event) {
    //    var keycode = (event.keyCode ? event.keyCode : event.which);
    //    if (keycode == '13') {
    //        $("#btnSearch").click();
    //    }
    //});

    $(document).ready(function () {
        Init();
        SetExtendedFields();
    });

    function Init() {
    }

    $(document).on("click", "[id='btnSearch']", function () {
        $("body").addClass("submit-progress-bg");
        $(".submit-progress").removeClass("hidden");

    });

    function Search() {

        $("body").removeClass("submit-progress-bg");
        $(".submit-progress").addClass("hidden");
    }
</script>

USDA.ARS.GRIN.GGTools.WebUI/Views/Taxonomy/CropForCWR/_Detail.cshtml
@model USDA.ARS.GRIN.GGTools.Taxonomy.ViewModelLayer.CropForCWRViewModelBase
<div id="section-folder-confirmation"></div>
@using (Html.BeginForm("Search", "CropForCWR", FormMethod.Post, new { id = "frmMain" }))
{
    @Html.HiddenFor(x => x.EventAction)
    @Html.HiddenFor(x => x.EventValue)
    @Html.HiddenFor(x => x.TableName)
    @Html.HiddenFor(x => x.TableCode)
    @Html.HiddenFor(x => x.PageTitle)
    @Html.HiddenFor(x => x.AuthenticatedUserCooperatorID)
    @Html.HiddenFor(x => x.ItemIDList)
    <div class="card">
        <div class="card-header p-2">
            <ul class="nav nav-pills">
                <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Search Criteria</a></li>
                <li class="nav-item"><a class="nav-link" href="#timeline" data-toggle="tab">Saved Searches</a></li>
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content">
                <div class="tab-pane active" id="activity">
                    <div id="section-search-criteria">

                        <div class="row">
                            @Html.Partial("~/Views/Components/_ShowHideButtons.cshtml")
                            <div class="col-md-11">
                                <div class="form-group">
                                    <label>Name</label>
                                    @Html.TextBoxFor(x => x.SearchEntity.Name, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        @Html.Partial("~/Views/Taxonomy/CropForCWR/_DetailExtended.cshtml")
                         

                    </div>
                    <div>
                        <button id="btnReset" type="button" class="btn btn-default">Reset</button>
                        <div class="btn-group float-right">
                            <button id="btnSearch" type="submit" class="btn btn-default">Search</button>
                            <button type="button" class="btn btn-default dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <div class="dropdown-menu" role="menu" style="">
                                <a id="btnOpenDynamicFolderModal" class="dropdown-item" href="#">Save Search</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="timeline">
                    <div class="row">
                        <div class="col-md-12">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

USDA.ARS.GRIN.GGTools.WebUI/Views/Taxonomy/CropForCWR/_DetailExtended.cshtml
@model USDA.ARS.GRIN.GGTools.Taxonomy.ViewModelLayer.CropForCWRViewModelBase

    <div id="section-extended-search-fields-body" style="display: none;">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group form-horizontal">
                    <label>Created By</label>
                    @Html.DropDownListFor(x => x.SearchEntity.CreatedByCooperatorID, Model.Cooperators, "All Cooperators", new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-horizontal">
                    <label>Created Date</label>
                    @Html.TextBoxFor(x => x.SearchEntity.CreatedDate, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group form-horizontal">
                    <label>Modified By</label>
                    @Html.DropDownListFor(x => x.SearchEntity.ModifiedByCooperatorID, Model.Cooperators, "All Cooperators", new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group form-horizontal">
                    <label>Modified Date</label>
                    @Html.TextBoxFor(x => x.SearchEntity.ModifiedDate, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-1">
                <div class="form-group form-horizontal">
                    <label>ID</label>
                    @Html.TextBoxFor(x => x.SearchEntity.ID, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-11">
                <div class="form-group form-horizontal">
                    <label>Note</label>
                    @Html.TextBoxFor(x => x.SearchEntity.Note, new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>

USDA.ARS.GRIN.GGTools.WebUI/Views/Taxonomy/CropForCWR/_List.cshtml
@model USDA.ARS.GRIN.GGTools.Taxonomy.ViewModelLayer.CropForCWRViewModel
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Crops For CWR (@Model.DataCollection.Count)</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fas fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="card-body">
        <table id="data_table_taxonomy_cwr_crop" class="table table-striped ggtools" style="width:100%;">
            <thead>
                <tr>
                    <th width="5%">ID</th>
                    <th>Name</th>
                    <th>Created</th>
                    <th>Created By</th>
                    <th>Last Modified</th>
                    <th>Modified By</th>
                    <th align="center" style="text-align:center;">Maps</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var result in Model.DataCollection)
                {
                <tr>
                    <td>
                        @result.ID
                    </td>
                    <td>@result.CropForCWRName</td>
                    <td>
                        @result.CreatedDate.ToShortDateString()
                    </td>
                    <td>
                        @result.CreatedByCooperatorName
                    </td>
                    <td>
                        @if (result.ModifiedDate > DateTime.MinValue)
                        {
                            @result.ModifiedDate.ToShortDateString()
                        }
                    </td>
                    <td>
                        @result.ModifiedByCooperatorName
                    </td>
                    <td align="center">
                        <a href="@Url.Action("Index","CWRMap", new { cropForCwrId = result.ID })">[@result.RelatedItemCount]</a>
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "CropForCWR", new { entityId = result.ID })" class="btn btn-default btn-sm float-right row-edit">
                            <i class="fa fa-edit"></i>
                        </a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>