USDA.ARS.GRIN.GGTools.WebUI/Controllers/SysGroupUserMapController.cs
using System;
using System.Web.Mvc;
using USDA.ARS.GRIN.GGTools.DataLayer;
using USDA.ARS.GRIN.GGTools.ViewModelLayer;
using NLog;

namespace USDA.ARS.GRIN.GGTools.WebUI.Controllers
{
    public class SysGroupUserMapController : BaseController, IController<SysGroupUserMap>
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();

        public PartialViewResult _Add()
        {
            SysGroupUserMapViewModel viewModel = new SysGroupUserMapViewModel();
            //TODO
            return PartialView("~/Views/SysGroupUserMap/_Widget.cshtml", viewModel);
        }

        public PartialViewResult _Delete()
        {
            SysGroupUserMapViewModel viewModel = new SysGroupUserMapViewModel();
            //TODO
            return PartialView("~/Views/SysGroupUserMap/_Widget.cshtml", viewModel);
        }


        public PartialViewResult _List(int sysUserId = 0, string isAvailable="")
        {
            SysGroupUserMapViewModel viewModel = new SysGroupUserMapViewModel();
            try
            {
                viewModel.SearchEntity.SysUserID = sysUserId;
                viewModel.GetBySysUser(sysUserId, isAvailable);
                return PartialView(viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }

        public PartialViewResult RenderWidget(int sysUserId)
        {
            SysGroupUserMapViewModel viewModel = new SysGroupUserMapViewModel();
            viewModel.GetBySysUser(sysUserId, "N");
            viewModel.GetBySysUser(sysUserId, "Y");
            return PartialView("~/Views/SysGroupUserMap/_Widget.cshtml", viewModel);
        }
        
        public PartialViewResult _ListFolderItems(int sysFolderId)
        {
            try
            {
                return PartialView("~/Views/Shared/_UnderConstruction.cshtml");
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }
        public ActionResult Delete(int entityId)
        {
            throw new NotImplementedException();
        }

        public ActionResult Delete(FormCollection formCollection)
        {
            throw new NotImplementedException();
        }

        public ActionResult Edit(int entityId)
        {
            throw new NotImplementedException();
        }

        public ActionResult Edit(SysGroupUserMap viewModel)
        {
            throw new NotImplementedException();
        }

        public PartialViewResult FolderItems(FormCollection formCollection)
        {
            throw new NotImplementedException();
        }

        // GET: SysGroupUserMap
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search(SysGroupUserMap viewModel)
        {
            throw new NotImplementedException();
        }

        public PartialViewResult _SelectList(int sysUserId = 0, int sysGroupId = 0)
        {
            SysGroupUserMapViewModel viewModel = new SysGroupUserMapViewModel();
            try
            {
                viewModel.SearchEntity.SysUserID = sysUserId;
                viewModel.SearchEntity.SysGroupID = sysGroupId;
                viewModel.Search();
                return PartialView(viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }
       
        public PartialViewResult RenderEditModal(int sysUserId)
        {
            SysGroupUserMapViewModel viewModel = new SysGroupUserMapViewModel();
            viewModel.Entity.SysUserID = sysUserId;
            viewModel.GetAvailableSysGroups();
            viewModel.GetCurrentSysGroups();
            return PartialView("~/Views/SysGroupUserMap/Modals/_Edit.cshtml", viewModel);
        }
        [HttpPost]
        public JsonResult AddSysGroups(FormCollection coll)
        {
            SysGroupUserMapViewModel viewModel = new SysGroupUserMapViewModel();
              
            try
            {
                if (!String.IsNullOrEmpty(coll["SysUserID"]))
                {
                    viewModel.Entity.SysUserID = Int32.Parse(coll["SysUserID"]);
                }

                if (!String.IsNullOrEmpty(coll["IDList"]))
                {
                    viewModel.ItemIDList = coll["IDList"];
                }

                string[] sysGroupIdListArray = viewModel.ItemIDList.Split(',');
                foreach (var sysGroupId in sysGroupIdListArray)
                {
                    viewModel.Entity.SysGroupID = Int32.Parse(sysGroupId.ToString());
                    viewModel.Entity.CreatedByCooperatorID = AuthenticatedUser.CooperatorID;
                    viewModel.Insert();
                }
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult DeleteSysGroups(FormCollection coll)
        {
            SysGroupUserMapViewModel viewModel = new SysGroupUserMapViewModel();

            try
            {
                if (!String.IsNullOrEmpty(coll["SysUserID"]))
                {
                    viewModel.Entity.SysUserID = Int32.Parse(coll["SysUserID"]);
                }

                if (!String.IsNullOrEmpty(coll["IDList"]))
                {
                    viewModel.ItemIDList = coll["IDList"];
                }
                // TODO
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult _ListAvailableSysGroups(FormCollection formCollection)
        {
            SysGroupUserMapViewModel viewModel = new SysGroupUserMapViewModel();

            if (!String.IsNullOrEmpty(formCollection["SysUserID"]))
            {
                viewModel.Entity.SysUserID = Int32.Parse(formCollection["SysUserID"]);
            }
            viewModel.GetAvailableSysGroups();
            return PartialView("~/Views/SysGroupUserMap/Modals/_ListAvailable.cshtml", viewModel);
        }

        [HttpPost]
        public ActionResult _ListCurrentSysGroups(FormCollection formCollection)
        {
            SysGroupUserMapViewModel viewModel = new SysGroupUserMapViewModel();

            if (!String.IsNullOrEmpty(formCollection["SysUserID"]))
            {
                viewModel.Entity.SysUserID = Int32.Parse(formCollection["SysUserID"]);
            }
            viewModel.GetCurrentSysGroups();
            return PartialView("~/Views/SysGroupUserMap/Modals/_ListCurrent.cshtml", viewModel);
        }
    }
}

USDA.ARS.GRIN.GGTools.WebUI/Views/SysGroupUserMap/Modals/_Edit - Copy.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.SysGroupUserMapViewModel
<div class="modal fade" id="modal-sys-group-user-map-edit" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                    <i class="fas fa-search"></i>
                    Edit Groups
                </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-5">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Can be Assigned To</h3>
                            </div>
                            <div id="section-available-sys-groups" class="card-body">
                                <table id="data-table-available-cooperators" class="table table-striped" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>Name</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @*@foreach (var result in Model.DataCollectionAvailableCooperators)
                                        {
                                            <tr>
                                                <td>
                                                    @result.ID
                                                </td>
                                                <td>
                                                    @result.FullName
                                                </td>
                                            </tr>
                                        }*@
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2" style="margin-top:5%;">
                        <button id="btnAdd" class="btn btn-default btn-block" type="button">>></button>
                        <button id="btnRemove" class="btn btn-default btn-block" type="button"><<</button>
                    </div>
                    <div class="col-md-5">
                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Currently Assigned To</h3>
                            </div>
                            <div id="section-current-sys-groups" class="card-body">
                                <table id="data-table-current-sys-groups" class="table table-striped" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>Name</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @*@foreach (var result in Model.DataCollectionCurrentCooperators)
                                        {
                                            <tr>
                                                <td>
                                                    @result.ID
                                                </td>
                                                <td>
                                                    @result.FullName
                                                </td>
                                            </tr>
                                        }*@
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    
</script>

USDA.ARS.GRIN.GGTools.WebUI/Views/SysGroupUserMap/Modals/_Edit.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.SysGroupUserMapViewModel
<div class="modal fade text-sm" id="modal-sys-group-user-map-edit" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                    <i class="fas fa-search"></i>
                    Assign Sys Groups
                </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <button id="btnAddSysGroups" class="btn btn-default btn-block">>></button>
                        <div id="section-available-sys-groups">
                            @Html.Partial("~/Views/SysGroupUserMap/Modals/_ListAvailable.cshtml")
                        </div>
                    </div>
                    <div class="col-md-6">
                        <button id="btnRemoveSysGroups" class="btn btn-default btn-block"><<</button>
                        <div id="section-current-sys-groups">
                            @Html.Partial("~/Views/SysGroupUserMap/Modals/_ListCurrent.cshtml")
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="btnCloseEditSysGroupUserMapModal" type="button" class="btn btn-default float-right" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#btnAddSysGroups").click(function () {
        var sysUserId = $("#Entity_SysUserID").val();
        AddSysGroups();
    });

    $("#btnRemoveSysGroups").click(function () {
        var sysUserId = $("#Entity_SysUserID").val();
        RemoveSysGroups();
        LoadAvailableSysGroups(sysUserId);
        LoadCurrentSysGroups(sysUserId);
    });

    $("#btnCloseEditSysGroupUserMapModal").click(function () {
        //DEBUG
        
    });

    function AddSysGroups() {
        var link = '@Url.Action("AddSysGroups", "SysGroupUserMap")';
        var sysUserId = $("#Entity_SysUserID").val();
        var selectedItemIdList = GetSelectedEntityIDs("data-table-available-sys-groups");
        var formData = new FormData();

        formData.append("SysUserID", sysUserId);
        formData.append("IDList", selectedItemIdList);

        $.ajax({
            url: link,
            type: 'POST',
            cache: false,
            dataType: 'json',
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                LoadAvailableSysGroups(sysUserId);
                LoadCurrentSysGroups(sysUserId);
            },
            error: function (ex) {
            }
        });
    }

    function RemoveSysGroups() {
        var link = '@Url.Action("DeleteSysGroups", "SysGroupUserMap")';
        var entityId = $("#Entity_ID").val();
        var selectedItemIdList = GetSelectedEntityIDs("data-table-current-sys-groups");
        var formData = new FormData();

        formData.append("FolderID", entityId);
        formData.append("IDList", selectedItemIdList);

        $.ajax({
            url: link,
            type: 'POST',
            cache: false,
            dataType: 'json',
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
            },
            error: function (ex) {
            }
        });
    }

    function LoadAvailableSysGroups(sysUserId) {
        var link = '@Url.Action("_ListAvailableSysGroups","SysGroupUserMap")';
        var formData = new FormData();

        formData.append("SysUserID", sysUserId);

        $.ajax({
            url: link,
            type: 'POST',
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (response) {
                $("#section-available-sys-groups").html(response);
            },
            error: function () {
                alert("Error loading available sys groups");
            }
        });
    }

    function LoadCurrentSysGroups(sysUserId) {
        var link = '@Url.Action("_ListCurrentSysGroups","SysGroupUserMap")';
        var formData = new FormData();

        formData.append("SysUserID", sysUserId);

        $.ajax({
            url: link,
            type: 'POST',
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (response) {
                $("#section-current-sys-groups").html(response);
            },
            error: function () {
                alert("Error loading current sys groups");
            }
        });
    }
</script>

USDA.ARS.GRIN.GGTools.WebUI/Views/SysGroupUserMap/Modals/_ListAvailable.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.SysGroupUserMapViewModel
<table id="data-table-available-sys-groups" class="table table-striped" style="width:100%;">
    <thead>
        <tr>
            <th></th>
            <th>ID</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var result in Model.DataCollectionAvailable)
        {
            <tr>
                <td>
                    @result.ID
                </td>
                <td>
                    @result.ID
                </td>
                <td>
                    @result.GroupTag
                </td>
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function () {
        InitDataTableLightMultiSelect("data-table-available-sys-groups");
    });
</script>

USDA.ARS.GRIN.GGTools.WebUI/Views/SysGroupUserMap/Modals/_ListCurrent.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.SysGroupUserMapViewModel
<table id="data-table-assigned-sys-groups" class="table table-striped" style="width:100%;">
    <thead>
        <tr>
            <th></th>
            <th>ID</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var result in Model.DataCollectionUnavailable)
        {
            <tr>
                <td>
                    @result.ID
                </td>
                <td>
                    @result.ID
                </td>
                <td>
                    @result.GroupTag
                </td>
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function () {
        InitDataTableLightMultiSelect("data-table-assigned-sys-groups");
    });
</script>

USDA.ARS.GRIN.GGTools.WebUI/Views/SysGroupUserMap/Modals/_Lookup.cshtml
@model USDA.ARS.GRIN.GGTools.ViewModelLayer.SysGroupUserMapViewModel
<div class="modal fade" id="modal-sys-table-lookup" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                    <i class="fas fa-search"></i>
                    Who Has Access?
                </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <table id="data_table_sys_permission" class="table table-striped ggtools" style="width:100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th>ID</th>
                            <th>Group</th>
                            <th>User Name</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                        </tr>
                    </thead>
                    <tbody>
                            @foreach (var result in Model.DataCollection)
                            {
                                <tr>
                                    <td>
                                        @result.ID
                                    </td>
                                    <td>@result.ID</td>
                                    <td>@result.GroupTag</td>
                                    <td>@result.SysUserName</td>
                                    <td>
                                        <a href="@Url.Action("Edit","Cooperator", new { @entityId = result.CooperatorID })">
                                            @result.FirstName
                                        </a>
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit","Cooperator", new { @entityId = result.CooperatorID })">
                                            @result.LastName
                                        </a>
                                    </td>
                                </tr>
                            }
                    </tbody>
                </table>
                <script type="text/javascript">
                    $(document).ready(function () {
                        InitDataTableLight("data_table_sys_permission");
                    });
                </script>

            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).on("click", "[id='btnShowTablePermissions']", function () {
        $("#modal-sys-table-lookup").modal("show");
    });
</script>